### PR TITLE
Validation after resolving refs

### PR DESCRIPTION
**Pull request by tansin**
Hello @seriousme, I think I found a bug. The validation of the specification on which `resolveRefs()` was called seems not to work. It was difficult for me to explain how to reproduce the bug, so I decided to simply add some more unit tests which reproduce the problem and exclude some suspected causes. You don't need to merge this PR. It is just for you to reproduce the bug. Of course you can use my PR if you want to add more tests. Feel free to change or extend it. Thank you for your important work and great project! 👍

### CODE REVIEW

**Comment by tansin** [comment]
I guess, I've also found a fix for the problem. Please review ;)

Background: the validator said, that there were occurrences of `$id` properties which were `undefined`. I realised that they were used for referencing and were not needed after inlining anymore. So they were set to `undefined`. But then the validator complained about references that were pointing to nowhere, which is correct. So my thought was to delete the properties - not just to set them `undefined` - so that the validator doesn't analyse them at all

**Comment by tansin** [comment]
And last but not least. I've fixed the `index.d.ts` file. Previously `addSpecRef()` was declared as sync. So I didn't call it asynchronously (I mean I didn't use `await`). Which was a mistake, because addSpecRef() is asynchronous. Now IDE and autocomplete show me the function as asynchronous

**Comment by seriousme** [comment]
Hi,

thanks for the bugreport and the patch! 
Can you please do a `npm run format` to fix the Biome formatter warnings ?

Kind regards,
Hans

**Comment by seriousme** [comment]
Thank you !

**Comment by seriousme** [comment]
Published as 2.1.5 on NPM

**Comment by tansin** [comment]
Thank you too!!

**Pull request merged**
